import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Exo_2 } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { ReactNode } from "react";
import { cn } from "@/lib/utils";

const exo_2 = Exo_2({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={cn("bg-black text-white dark:bg-white dark:text-gray-900",exo_2.className)}>
        <Navbar />
        <main className="min-h-screen pt-16 px-4 max-w-7xl mx-auto">
          {children}
        </main>
        
      </body>
    </html>
  );
}